[ping]
schedule = "*/5 * * * *"

#
# FYI: Above we could've said:
#
#   param = {destinations = [...]}
#
# ...but that'd be a long one-liner.
#
# TOML only lets our nested list split over multiple lines if we un-nest it,
# with the below implicitly-nested table.
#
# (YAML is of course quite different!
# ...And we support YAML configuration files as well.)
#

[ping.param]
# list of network locators
#
# (OR dict of network locator: results label)
destinations = [
    "google.com",
    "netflix.com",
    "nytimes.com",
    "facebook.com",
    "reddit.com",
    "github.com",
    "linkedin.com",
]


[traceroute]
schedule = "*/5 * * * *"

[traceroute.param]
targets = [
    "1.1.1.1",
    "nytimes.com",
]
