[tool.poetry]
name = "netrics-measurements"
version = "0.0.1"
description = "The extensible network measurements framework"
license = "MIT"
authors = [
  "Jesse London <jesselondon@gmail.com>",
  "Kyle MacMillan <macmillan@uchicago.edu>",
]
packages = [{include = "netrics", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
argcmdr = "^0.7.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
netrics = "netrics:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
