name: Build PYZ distribution

on:
  release:
    types:
      - published

jobs:
  build:
    uses: internet-equity/fate-pyz/.github/workflows/build-pyz.yml@0.4.2
    permissions:
      contents: write
    with:
      app-main: netrics
      app-alts: netrics.+
      app-solo: false
