name: Build PYZ distribution

run-name: ${{ github.event.release.tag_name || inputs.head-sha || github.event.workflow_run.display_title }}

on:
  release:
    types:
      - published

  workflow_run:
    workflows:
      - publish
    types:
      - completed

  workflow_dispatch:
    inputs:
      head-sha:
        default: ""
        required: false
        type: string
        description: Non-default changeset to build

jobs:
  setup:
    runs-on: ubuntu-latest

    outputs:
      release-sha: ${{ steps.head.outputs.release-sha }}
      can-build: ${{ steps.success.outputs.can-build }}

    steps:
      - name: Check success
        id: success
        env:
          CONCLUSION: ${{ github.event.workflow_run && github.event.workflow_run.conclusion || 'success' }}
        run: |
          if [ "$CONCLUSION" = success ]
          then
            echo "publish successful"
            echo "can-build=true" >> $GITHUB_OUTPUT
          else
            echo "::error::publish not successful"
            echo "can-build=false" >> $GITHUB_OUTPUT
          fi

      - name: Check out repository
        uses: actions/checkout@v3
        if: fromJSON(steps.success.outputs.can-build)
        with:
          # fetch enough that we should feasibly be able to find this changeset
          # and its subsequent tag commit (but without fetching *everything*)
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 100
          fetch-tags: true

      - name: Determine HEAD
        id: head
        if: fromJSON(steps.success.outputs.can-build)
        env:
          HEAD_SHA: ${{ inputs.head-sha }}
          RUN_SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          TARGET_SHA=${HEAD_SHA:-$RUN_SHA}

          HEAD="$(git log --format=%H ${TARGET_SHA}.. | tail -n 1)"

          if [ -z "$HEAD" ]
          then
            echo "::error::could not find publish workflow changeset following ${TARGET_SHA:0:9}"
            exit 1
          fi

          # Though we've fetched plenty of *commits* above, we can't rely on having all *tags*
          # So instead we'll query the remote.
          TAGS="$(git ls-remote --tags --refs --quiet | grep -E "^${HEAD}\s+" | awk '{print $2}' | awk -F / '{print $3}')"

          if [ -z "$TAGS" ]
          then
            echo "::error::changeset following ${TARGET_SHA:0:9} does not appear to be tagged release: ${HEAD:0:9}"
            exit 1
          fi

          echo "publish workflow release SHA: $HEAD:" $TAGS

          echo "release-sha=$HEAD" >> $GITHUB_OUTPUT

  delegate:
    needs: [setup]
    uses: internet-equity/fate-pyz/.github/workflows/build-pyz.yml@0.6.7
    if: fromJSON(needs.setup.outputs.can-build)
    permissions:
      contents: write
    with:
      app-main: netrics
      app-alts: netrics.+
      app-solo: false
      head-sha: ${{ needs.setup.outputs.release-sha }}
